# Generated by Django 5.2.4 on 2025-07-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BriaAPILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_body', models.TextField()),
                ('response_time', models.FloatField()),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('cost', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ImageGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('enhanced_prompt', models.TextField(blank=True)),
                ('parameters', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'In queue'), ('processing', 'Processing'), ('completed', 'Complete'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('bria_response', models.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('template', models.TextField()),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
