# Generated by Django 5.2.4 on 2025-07-18 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image_gen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegenerationjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='briaapilog',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='image_gen.imagegenerationjob'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='imagegenerationjob',
            index=models.Index(fields=['status'], name='image_gen_i_status_abda9c_idx'),
        ),
        migrations.AddIndex(
            model_name='imagegenerationjob',
            index=models.Index(fields=['-created_at'], name='image_gen_i_created_19af56_idx'),
        ),
    ]
