# Generated by Django 5.2.4 on 2025-07-18 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='imagegenerationjob',
            name='image_gen_i_created_19af56_idx',
        ),
        migrations.AlterField(
            model_name='imagegenerationjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='imagegenerationjob',
            index=models.Index(fields=['user', '-created_at'], name='image_gen_i_user_id_1fbb58_idx'),
        ),
    ]
